baseURL: https://bpalas.netlify.app/
theme: hugobricks
defaultContentLanguage: en
assetDir: assets

caches:
  images:
    dir: :cacheDir/images

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content
    weight: 1
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /services/:slug
        products: /webshop/:slug
      section:
        posts: /blog/
        services: /services/
        products: /webshop/
  