[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "hugo v0.145.0-666444f0a52132f9fec9f71cf25b441cc6a4f355+extended windows/amd64 BuildDate=2025-02-26T15:41:25Z VendorInfo=gohugoio"

  